### ISSUE TITLE
Stopped working on HA 2021.12

### ISSUE THREAD

**Issue by ildar170975** [Cheaterdev/clear_grass-ha#11]
After upgrade to HA 2021.12 the integration stopped working.
There are messages in Log:
```
2021-12-12 04:00:57 WARNING (MainThread) [homeassistant.components.sensor] Platform clear_grass not ready yet: None; Retrying in background in 30 seconds
2021-12-12 04:00:57 WARNING (MainThread) [homeassistant.components.sensor] Platform clear_grass not ready yet: None; Retrying in background in 30 seconds
```
and the sensors are not created.

**Comment by Cheaterdev** [comment]
Sorry but I don't have  the ability to fix this issue right now. 
Probably miio library was changed on which my custom integration is based.

BTW this device should be already supported by official miio integration::
https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-air-quality-monitor

I see that their code was improved to handle this device:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/air_quality.py

**Comment by Cheaterdev** [comment]
I can confirm that this device works after adding it to HA through "Xiaomi Miio" integration from "Integrations" page. Does not even need any yaml configuration for it

**Comment by ildar170975** [comment]
Regarding Xiaomi Miio integration:
Air Quality Monitor reports empty "charging" attribute 
https://github.com/home-assistant/core/issues/61533

**Comment by ildar170975** [comment]
> Sorry but I don't have the ability to fix this issue right now.
> Probably miio library was changed on which my custom integration is based.

Probably you may be able to help with that issue?
https://github.com/home-assistant/core/issues/61533

**Comment by Cheaterdev** [comment]
Its not a `sensor` in the official integration but `air_quality`
Under `sensor `its probably some other entity like from network discovery (I have it too)

I have my device under `air_quality.qingping_air_monitor` name
So sensor templates are now:
`{{states.air_quality.qingping_air_monitor.attributes.carbon_dioxide}}`

**Comment by ildar170975** [comment]
The Xiaomi Miio creates 2 entities:
![изображение](https://user-images.githubusercontent.com/71872483/145896653-207ac685-f46c-4b59-9508-d74eb8e4cce0.png)
![изображение](https://user-images.githubusercontent.com/71872483/145896734-c93590b4-a7af-4b26-97b1-65504159d04c.png)
As for AQ data - yes, it is available in `air_quality` entity (initially the entity has a `cgllc_airmonitor_s1` name - I manually renamed it to `xiaomi_cg_1` to ensure my template sensors are getting data from this new entity).
All battery info is in the 2nd entity (which is of `unknown` state because of unknown reasons), and this entity has `null` for `charging`.

**Comment by ildar170975** [comment]
https://github.com/Cheaterdev/clear_grass-ha/pull/12
The integration seems to work again!
