### ISSUE TITLE
Stopped working in 2024.2: Requirements for clear_grass not found: ['construct==2.9.45']

### ISSUE THREAD

**Issue by ildar170975** [Cheaterdev/clear_grass-ha#15]
Starting from 2024.2 there is an error in Log:

2024-02-10 01:26:03.288 ERROR (MainThread) [homeassistant.config] Platform error: sensor - Requirements for clear_grass not found: ['construct==2.9.45'].

Also:

[homeassistant.util.package] Unable to install package construct==2.9.45: error: subprocess-exited-with-error

The `cleargrass_ha` sensors are not created.

**Comment by ildar170975** [comment]
Here is how I fixed it locally in `manifest.json`:
```
  "requirements": [
    "construct==2.10.68",
```
But I am not sure that this is a 100% correct solution.

**Comment by Cheaterdev** [comment]
Hi! If it works - it's OK. Have no possibility to check it on my home setup, so I'll take your proposal as the fix :)

**Comment by ildar170975** [comment]
@Cheaterdev 
Welcome back!
Could you also take a look at my a bit cleaned up component here?
https://github.com/Cheaterdev/clear_grass-ha/issues/13#issuecomment-1860095768

**Comment by ildar170975** [comment]
Seems to be solved by https://github.com/Cheaterdev/clear_grass-ha/commit/6867c12ce492384aa79cd24a5657f0bd573b2060
