### ISSUE TITLE
Wrong tVOC value

### ISSUE THREAD

**Issue by oleonov** [Cheaterdev/clear_grass-ha#3]
On my device I have 1312, but inside home assistant I see tvoc: 286
What can I do to fix this bug?

**Comment by egorzumbeispiel** [comment]
Not bug.
Разные единицы измерения, в самом устройстве несколько параметров, но в HA попадает этот (ppb). Сделайте темплейт для пересчёта, у вас 1312 мг/м³ и 286 ppb.
Будет что-то типа (286/250)*1000=1144

**Comment by oleonov** [comment]
Понял, спасибо)
